version: "3"
services: 
    api:
        image: ericlau1987/fastapi
        depends_on: 
            - postgres
        ports: 
            - 80:8000
        # volumes:
        #     - ./:/Users/liuyifu/src/app:ro

        # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        # env_file:
        #   - ./.env
        environment:
        - database_hostname=${DATABASE_HOSTNAME} 
        - database_port=${DATABASE_PORT} 
        - database_password=${DATABASE_PASSWORD}
        - database_name=${DATABASE_PASSWORD}
        - database_username=${DATABASE_USERNAME}
        - secret_key=${SECRET_KEY}
        - algorithm=${ALGORITHM} 
        - access_token_expire_minutes=${ACCESS_TOKEN_EXPIRE_MINUTES}

    postgres:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
          - POSTGRES_DB=${DATABASE_PASSWORD}
      volumes:
        - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: